### ISSUE TITLE
Mk install - Error

### ISSUE THREAD

**Issue by jspreis** [telephil9/lua9#1]
After cloning repo, mk install returned following error:
"cpu% mk install
pcc -c -I. -D_C99_SNPRINTF_EXTENSION -D_PLAN9_SOURCE -D_POSIX_SOURCE -D_SUSV2_SOURCE -DLUA_POSIX -DENABLE_CJSON_GLOBAL -DPlan9 -DMAKE_LUA lua9.c
cpp: lua9.c:8 Could not find include file "lua.h"
pcc: 8c: cpp 4385: error
<eof> syntax error, last name: Fon
mk: pcc -c -I. ...  : exit status=rc 4381: pcc 4383: 8c: cpp 4385: error"

Arch: 386, 9front.

**Comment by telephil9** [comment]
It seems you did not install the lua 5.4 port first.

To do so:
```
git/clone git://github.com/staalmannen/lua
cd lua
mk install
```

I've updated README.md accordingly.

**Comment by jspreis** [comment]
Cool! Thanks!
